namespace SpriteKind {
    export const Signpost = SpriteKind.create()
    export const Trap = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    for (let index = 0; index < tileSize; index++) {
        mySprite.y += 0 - 1
    }
    gameState = "enemyTurn"
})
function monsterMove (monster: Sprite) {
    if (randint(0, 1) == 0) {
        if (comX < 0) {
            monster.x += -16
        }
        if (comX > 0) {
            monster.x += 16
        }
    } else {
        if (comY < 0) {
            monster.y += -16
        }
        if (comY > 0) {
            monster.y += 16
        }
    }
}
function startNextRoom () {
    sprites.destroyAllSpritesOfKind(SpriteKind.Signpost)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    roomNumber += 1
    randomRoom = randint(1, 4)
    if (randomRoom == 1) {
        sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
        tiles.loadMap(tiles.createMap(tilemap`level1`))
        if (gameState == "enemyTurn") {
            gameState = "playerTurn"
        }
    }
    if (randomRoom == 2) {
        sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
        tiles.loadMap(tiles.createMap(tilemap`room4`))
        if (gameState == "enemyTurn") {
            gameState = "playerTurn"
        }
    }
    if (randomRoom == 3) {
        sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
        tiles.loadMap(tiles.createMap(tilemap`room1`))
        if (gameState == "enemyTurn") {
            gameState = "playerTurn"
        }
    }
    if (randomRoom == 4) {
        sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
        tiles.loadMap(tiles.createMap(tilemap`room0`))
        if (gameState == "enemyTurn") {
            gameState = "playerTurn"
        }
    }
    gameState = "playerTurn"
}
function monsterAttack (monster: Sprite) {
    animation.runImageAnimation(
    monster,
    [img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .....fffc1111111f.......
        ...fc111cd1111111f......
        ...f1b1b1b1111dddf......
        ...fbfbffcf11fcddf......
        ......fcf111111bbf......
        .......ccbdb1b1fcf......
        .......fffbfbfdff.......
        ........ffffffff........
        ........fffffffffff.....
        .........fffffc111cf....
        .........fffff1b1b1f....
        ..........ffffbfbfbf....
        ...........ffff.........
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ....7.fd11111111df......
        ...7..fd11111111df......
        ...7..fd11111111df......
        ...7..fddd1111dddff.....
        ...77.fbdbfddfbdbfcf....
        ...777fcdcf11fcdcfbf....
        ....77fffbdb1bdffcf.....
        ....fcb1bcffffff........
        ....f1c1c1ffffff........
        ....fdfdfdfffff.........
        .....f.f.f..............
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd111111111f......
        ......fd11111111df......
        ......fd11111111df......
        ......fcdd1111ddcff.....
        .......fbcf11fcbfbbf....
        .......ffbdb1bdffff.....
        ........fcbfbfdf........
        ........ffffffff........
        ......ffffffffff........
        .....fcb1bcffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fdd111111ddf......
        ......fbdd1111dddf......
        ......fcdbfddfbdbf......
        .......fbcf11fcbfff.....
        .......ffb1111bcfbcf....
        ........fcdb1bdfbbbf....
        .......ffffffffffcf.....
        .....fcb1bcfffff........
        .....f1b1b1ffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    500,
    false
    )
    monster.setImage(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `)
    changePlayerHealth(-10)
}
function changePlayerHealth (num: number) {
    statusbar.value += num
    if (statusbar.value <= 0) {
        game.setGameOverMessage(false, "You died")
        game.setGameOverEffect(false, effects.splatter)
        game.gameOver(false)
    }
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    gameState = "enemyTurn"
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava0, function (sprite, location) {
    if (gameState == "enemyTurn") {
        changePlayerHealth(-5)
    }
})
function checkPosition () {
    for (let value of sprites.allOfKind(SpriteKind.Signpost)) {
        if (tiles.locationXY(tiles.locationOfSprite(mySprite), tiles.XY.column) == tiles.locationXY(tiles.locationOfSprite(value), tiles.XY.column)) {
            roomItem = sprites.readDataString(value, "rewardType")
        }
    }
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    for (let index = 0; index < tileSize; index++) {
        mySprite.x += 0 - 1
    }
    gameState = "enemyTurn"
    checkPosition()
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.doorClosedNorth, function (sprite, location) {
    startNextRoom()
})
tiles.onMapLoaded(function (tilemap2) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Signpost)
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.collectibleInsignia)
    for (let value2 of tiles.getTilesByType(sprites.dungeon.doorClosedNorth)) {
        rewardIs = rewardList._pickRandom()
        if (rewardIs == "health") {
            rewardSprite = sprites.create(img`
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                .......22...22......
                ......2322.2222.....
                ......232222222.....
                ......222222222.....
                .......22222b2......
                ........222b2.......
                .........222........
                ..........2.........
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                `, SpriteKind.Signpost)
            sprites.setDataString(rewardSprite, "rewardType", rewardIs)
            tiles.placeOnTile(rewardSprite, tiles.locationInDirection(value2, CollisionDirection.Top))
        }
        if (rewardIs == "shop") {
            rewardSprite = sprites.create(img`
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                .......444ee........
                .......4eecce.......
                ........ecfc........
                .........ec.........
                .......ee4eee.......
                ......e44eeeec......
                .....e4eeeeeeec.....
                .....e4eeeeeeec.....
                ....e4eeeeeeeecf....
                ....e4eeeeeeeccf....
                ....eeeeeeeeccff....
                .....ceecccccff.....
                ......ccccffff......
                ....................
                `, SpriteKind.Signpost)
            sprites.setDataString(rewardSprite, "rewardType", rewardIs)
            tiles.placeOnTile(rewardSprite, tiles.locationInDirection(value2, CollisionDirection.Top))
            rewardSprite.setScale(0.6, ScaleAnchor.Middle)
        }
        if (rewardIs == "boost") {
            rewardSprite = sprites.create(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . f . . . . . . . 
                . . . . . . . . c . . . . . . . 
                . . . . . . . c d c . . . . . . 
                . . . . f . . c d c . . f . . . 
                . . . . . c . b 5 b . c . . . . 
                . . . . . . b d 5 d b . . . . . 
                . . . c c b d 5 1 5 d b c c . . 
                . f c d d 5 5 1 1 1 5 5 d d c f 
                . . . c c b d 5 1 5 d b c c . . 
                . . . . . . b d 5 d b . . . . . 
                . . . . . c . b 5 b . c . . . . 
                . . . . f . . c d c . . f . . . 
                . . . . . . . c d c . . . . . . 
                . . . . . . . . c . . . . . . . 
                . . . . . . . . f . . . . . . . 
                `, SpriteKind.Signpost)
            sprites.setDataString(rewardSprite, "rewardType", rewardIs)
            tiles.placeOnTile(rewardSprite, tiles.locationInDirection(value2, CollisionDirection.Top))
            rewardSprite.setScale(0.6, ScaleAnchor.Middle)
        }
        if (rewardIs == "item") {
            rewardSprite = sprites.create(img`
                ....................
                ....................
                ....................
                ....................
                ..............1d....
                .............1bd....
                ............1bd.....
                ...........1bd......
                ..........1bd.......
                .........1bd........
                ....e...1bd.........
                ....ee.1bd..........
                .....eecd...........
                .....c9c............
                ....eccce...........
                ....cc..ce..........
                ....................
                ....................
                ....................
                ....................
                `, SpriteKind.Signpost)
            sprites.setDataString(rewardSprite, "rewardType", rewardIs)
            tiles.placeOnTile(rewardSprite, tiles.locationInDirection(value2, CollisionDirection.Top))
        }
        if (rewardIs == "gold") {
            rewardSprite = sprites.create(img`
                . . b b b b . . 
                . b 5 5 5 5 b . 
                b 5 d 3 3 d 5 b 
                b 5 3 5 5 1 5 b 
                c 5 3 5 5 1 d c 
                c d d 1 1 d d c 
                . f d d d d f . 
                . . f f f f . . 
                `, SpriteKind.Signpost)
            sprites.setDataString(rewardSprite, "rewardType", rewardIs)
            tiles.placeOnTile(rewardSprite, tiles.locationInDirection(value2, CollisionDirection.Top))
        }
    }
    if (roomNumber >= 1) {
        for (let value3 of tiles.getTilesByType(sprites.dungeon.floorMixed)) {
            monster = sprites.create(img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ......fd11111111df......
                ......fddd1111dddf......
                ......fbdbfddfbdbf......
                ......fcdcf11fcdcf......
                .......fb111111bf.......
                ......fffcdb1bdffff.....
                ....fc111cbfbfc111cf....
                ....f1b1b1ffff1b1b1f....
                ....fbfbffffffbfbfbf....
                .........ffffff.........
                ...........fff..........
                ........................
                ........................
                ........................
                ........................
                `, SpriteKind.Enemy)
            tiles.placeOnTile(monster, value3)
            console.log(monster)
        }
    }
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    for (let index = 0; index < tileSize; index++) {
        mySprite.x += 1
    }
    gameState = "enemyTurn"
    checkPosition()
})
function triggerTraps (enemySprite: Sprite) {
	
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava1, function (sprite, location) {
    if (gameState == "enemyTurn") {
        changePlayerHealth(-5)
    }
})
function monsterTurn (monsterSprite: Sprite) {
    comX = mySprite.x - monsterSprite.x
    comY = mySprite.y - monsterSprite.y
    if (Math.abs(comX) == 16 && Math.abs(comY) == 0 || Math.abs(comX) == 0 && Math.abs(comY) == 16) {
        monsterAttack(monsterSprite)
    } else {
        monsterMove(monsterSprite)
    }
}
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    for (let index = 0; index < tileSize; index++) {
        mySprite.y += 1
    }
    gameState = "enemyTurn"
})
function checkAdjacent (sprite1: Sprite, sprite2: Sprite) {
    if (tiles.locationXY(tiles.locationOfSprite(sprite1), tiles.XY.column) == tiles.locationXY(tiles.locationOfSprite(sprite2), tiles.XY.column)) {
        if (tiles.locationXY(tiles.locationOfSprite(sprite1), tiles.XY.row) - tiles.locationXY(tiles.locationOfSprite(sprite2), tiles.XY.row) == 1) {
            console.log("top")
        }
    }
}
let monster: Sprite = null
let rewardSprite: Sprite = null
let rewardIs = ""
let randomRoom = 0
let comY = 0
let comX = 0
let rewardList: string[] = []
let statusbar: StatusBarSprite = null
let mySprite: Sprite = null
let tileSize = 0
let gameState = ""
let roomNumber = 0
let roomItem = ""
roomItem = ""
roomNumber = 0
gameState = "playerTurn"
tiles.loadMap(tiles.createMap(tilemap`roomStart`))
if (tiles.getLoadedMap() == tiles.createMap(tilemap`roomStart`)) {
    if (gameState == "enemyTurn") {
        gameState = "playerTurn"
    }
}
tileSize = 16
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 4 f 2 2 2 2 2 2 f 4 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
mySprite.setScale(0.9, ScaleAnchor.Middle)
scene.cameraFollowSprite(mySprite)
statusbar = statusbars.create(100, 3, StatusBarKind.Health)
statusbar.positionDirection(CollisionDirection.Top)
statusbar.setColor(6, 2, 15)
rewardList = [
"health",
"shop",
"boost",
"item",
"gold"
]
game.onUpdate(function () {
    if (gameState == "enemyTurn") {
        for (let value4 of sprites.allOfKind(SpriteKind.Enemy)) {
            monsterTurn(value4)
        }
        for (let value5 of sprites.allOfKind(SpriteKind.Trap)) {
            triggerTraps(value5)
        }
        gameState = "playerTurn"
    }
})
